apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-v2
  labels:
    name: frontend
spec:
  replicas: 2
  selector:
    name: play-frontend
  template:
    metadata:
      labels:
        name: play-frontend
    spec:
      containers:
        -
          name: play-frontend
          image: "eu.gcr.io/pdf-cropper/play:latest"
          ports:
            -
              containerPort: 9000
              protocol: TCP


